; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = genericSTM32C092FB

[env:genericSTM32C092FB]
platform = ststm32
board = genericSTM32C092FB
framework = arduino
board_build.ldscript = STM32C092FBP6_FLASH.ld
board_build.variants_dir = variants

; 1. Force PlatformIO to download the latest core with C092 support
platform_packages = 
    framework-arduinoststm32 @ https://github.com/stm32duino/Arduino_Core_STM32.git

upload_protocol = custom
upload_command = ./pio_openocd.sh -c "program {$SOURCE} 0x08000000 verify reset; shutdown"

build_type = debug
debug_tool = custom
debug_port = localhost:3333
debug_server =
    ./pio_openocd.sh

debug_init_cmds =
    target extended-remote $DEBUG_PORT
    monitor reset halt
    monitor halt
    monitor arm semihosting disable
    delete breakpoints
debug_load_mode = always

; 2. Explicitly tell the HAL which chip we are using
build_flags = 
    -D STM32C092xx
    -D configTOTAL_HEAP_SIZE=6144
  -D configMEMMANG_HEAP_NB=4

lib_deps =
    stm32duino/STM32duino FreeRTOS
